export const products = [
  {
    id: "med-001",
    name: "Acetaminophen 500mg",
    description: "Pain reliever and fever reducer",
    price: 8.99,
    category: "pain relief",
    stock: 45,
    requiresPrescription: false,
  },
  {
    id: "med-002",
    name: "Ibuprofen 200mg",
    description: "Anti-inflammatory pain reliever",
    price: 7.49,
    category: "pain relief",
    stock: 38,
    requiresPrescription: false,
  },
  {
    id: "med-003",
    name: "Amoxicillin 500mg",
    description: "Antibiotic for bacterial infections",
    price: 15.99,
    category: "antibiotics",
    stock: 20,
    requiresPrescription: true,
  },
  {
    id: "med-004",
    name: "Lisinopril 10mg",
    description: "ACE inhibitor for high blood pressure",
    price: 12.99,
    category: "heart health",
    stock: 25,
    requiresPrescription: true,
  },
  {
    id: "med-005",
    name: "Atorvastatin 20mg",
    description: "Statin medication for cholesterol",
    price: 18.49,
    category: "heart health",
    stock: 18,
    requiresPrescription: true,
  },
  {
    id: "med-006",
    name: "Cetirizine 10mg",
    description: "Antihistamine for allergies",
    price: 9.99,
    category: "allergies",
    stock: 32,
    requiresPrescription: false,
  },
  {
    id: "med-007",
    name: "Fluticasone Nasal Spray",
    description: "Steroid nasal spray for allergies",
    price: 21.99,
    category: "allergies",
    stock: 15,
    requiresPrescription: false,
  },
  {
    id: "med-008",
    name: "Metformin 500mg",
    description: "Oral diabetes medication",
    price: 14.49,
    category: "diabetes",
    stock: 22,
    requiresPrescription: true,
  },
  {
    id: "med-009",
    name: "Omeprazole 20mg",
    description: "Proton pump inhibitor for acid reflux",
    price: 11.99,
    category: "digestive health",
    stock: 28,
    requiresPrescription: false,
  },
  {
    id: "med-010",
    name: "Multivitamin Daily",
    description: "Complete multivitamin supplement",
    price: 13.99,
    category: "vitamins",
    stock: 40,
    requiresPrescription: false,
  },
  {
    id: "med-011",
    name: "Vitamin D3 1000IU",
    description: "Vitamin D supplement",
    price: 10.49,
    category: "vitamins",
    stock: 35,
    requiresPrescription: false,
  },
  {
    id: "med-012",
    name: "Levothyroxine 50mcg",
    description: "Thyroid hormone replacement",
    price: 16.99,
    category: "hormones",
    stock: 18,
    requiresPrescription: true,
  },
  {
    id: "med-013",
    name: "Albuterol Inhaler",
    description: "Bronchodilator for asthma",
    price: 24.99,
    category: "respiratory",
    stock: 12,
    requiresPrescription: true,
  },
  {
    id: "med-014",
    name: "Hydrocortisone Cream 1%",
    description: "Anti-itch cream for skin irritation",
    price: 8.49,
    category: "skin care",
    stock: 30,
    requiresPrescription: false,
  },
  {
    id: "med-015",
    name: "Digital Thermometer",
    description: "For measuring body temperature",
    price: 12.99,
    category: "medical devices",
    stock: 15,
    requiresPrescription: false,
  },
  {
    id: "med-016",
    name: "Blood Pressure Monitor",
    description: "Automatic blood pressure monitor",
    price: 49.99,
    category: "medical devices",
    stock: 8,
    requiresPrescription: false,
  },
  {
    id: "med-017",
    name: "Glucose Test Strips",
    description: "For blood glucose monitoring",
    price: 29.99,
    category: "diabetes",
    stock: 20,
    requiresPrescription: false,
  },
  {
    id: "med-018",
    name: "First Aid Kit",
    description: "Basic first aid supplies",
    price: 19.99,
    category: "first aid",
    stock: 25,
    requiresPrescription: false,
  },
  {
    id: "med-019",
    name: "Bandages Variety Pack",
    description: "Assorted adhesive bandages",
    price: 6.99,
    category: "first aid",
    stock: 42,
    requiresPrescription: false,
  },
  {
    id: "med-020",
    name: "Cough Syrup",
    description: "For relief of cough and cold symptoms",
    price: 11.49,
    category: "cold and flu",
    stock: 33,
    requiresPrescription: false,
  },
  {
    id: "med-021",
    name: "Nasal Decongestant",
    description: "Relieves nasal congestion",
    price: 9.99,
    category: "cold and flu",
    stock: 27,
    requiresPrescription: false,
  },
  {
    id: "med-022",
    name: "Melatonin 5mg",
    description: "Sleep aid supplement",
    price: 12.49,
    category: "sleep aids",
    stock: 22,
    requiresPrescription: false,
  },
  {
    id: "med-023",
    name: "Probiotic Capsules",
    description: "Supports digestive health",
    price: 23.99,
    category: "digestive health",
    stock: 18,
    requiresPrescription: false,
  },
  {
    id: "med-024",
    name: "Hand Sanitizer",
    description: "Kills 99.9% of germs",
    price: 4.99,
    category: "personal care",
    stock: 50,
    requiresPrescription: false,
  },
]
